package main

import "net/http"

func applicationStyleHandler(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "text/css; charset=utf-8")
	w.Header().Set("Cache-Control", "public, max-age=300")
	_, _ = w.Write([]byte(applicationStyle))
}

const applicationStyle = `
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;--bg:#080d18;--surface:#111827;--surface-2:#172033;--line:#293449;--text:#eef2ff;--muted:#94a3b8;--accent:#3b82f6;--accent-strong:#2563eb;--success:#34d399;--danger:#f87171}
*{scrollbar-color:#475569 transparent}
body{max-width:1180px;margin:0 auto;padding:28px 24px 56px;background:radial-gradient(circle at 15% -10%,rgb(37 99 235 / 18%),transparent 34rem),var(--bg)!important;color:var(--text)!important;line-height:1.5}
.main-nav{position:sticky;top:14px;z-index:20;display:flex!important;align-items:center;gap:6px;margin:0 0 18px!important;padding:8px!important;border:1px solid rgb(71 85 105 / 65%)!important;border-radius:16px!important;background:rgb(15 23 42 / 88%)!important;box-shadow:0 18px 50px rgb(0 0 0 / 28%)!important;backdrop-filter:blur(14px)}
.main-nav .brand{display:flex;align-items:center;gap:7px;margin:0 auto 0 8px!important;color:#fff!important;font-size:1.05rem;font-weight:750!important;letter-spacing:-.01em!important}.main-nav .brand:before{content:"";width:10px;height:10px;border-radius:50%;background:var(--accent);box-shadow:0 0 18px var(--accent)}.main-nav .brand small{padding:2px 7px;border:1px solid #334155;border-radius:999px;color:#bfdbfe;font-size:.68rem;font-weight:650}
.main-nav>a{padding:9px 12px!important;border:1px solid transparent;border-radius:10px!important;color:#b8c3d6!important;font-size:.9rem;font-weight:600;text-decoration:none;transition:background .15s,border-color .15s,color .15s,transform .15s}.main-nav>a:hover{border-color:#334155;background:#1e293b!important;color:#fff!important;transform:translateY(-1px)}.main-nav>a.active{border-color:rgb(96 165 250 / 38%);background:linear-gradient(135deg,#2563eb,#1d4ed8)!important;color:#fff!important;box-shadow:0 6px 16px rgb(37 99 235 / 24%)}
#internet-status{margin-right:8px;padding:5px 9px;border:1px solid #334155;border-radius:999px;background:#0f172a;font-size:.78rem;font-weight:650;white-space:nowrap}
#network-info{display:flex!important;align-items:center;flex-wrap:wrap;gap:10px!important;margin:0 8px 34px!important;padding:8px 12px;border:1px solid rgb(51 65 85 / 72%);border-top:0;border-radius:0 0 12px 12px;background:rgb(15 23 42 / 58%);color:var(--muted)!important;font-size:.82rem!important}#network-addresses{min-width:0;overflow:hidden;text-overflow:ellipsis}#update-app-state{color:#bfdbfe}
h1{margin:0 0 20px!important;color:#f8fafc;font-size:clamp(1.65rem,3vw,2.35rem);line-height:1.15;letter-spacing:-.035em}h2{letter-spacing:-.02em}p{color:#cbd5e1}.hint{color:var(--muted)!important}
table{width:100%;overflow:hidden;border:1px solid var(--line);border-collapse:separate!important;border-spacing:0!important;border-radius:14px;background:rgb(17 24 39 / 88%)!important;box-shadow:0 16px 44px rgb(0 0 0 / 18%)}th,td{padding:13px 14px!important;border-bottom:1px solid var(--line)!important;text-align:left}th{background:#151f31;color:#9fc5ff!important;font-size:.74rem;font-weight:750;letter-spacing:.055em;text-transform:uppercase}tbody tr:last-child td{border-bottom:0!important}tbody tr{transition:background .15s}tbody tr:hover{background:#18243a!important}td{color:#dbe4f0}td small{color:var(--muted)}code{color:#86efac!important;font-family:"Cascadia Code","SFMono-Regular",Consolas,monospace;font-size:.88em}
button,input,select{box-sizing:border-box;min-height:40px;padding:9px 13px;border:1px solid #3b485f;border-radius:9px!important;font:inherit}button{border-color:#3b82f6!important;background:linear-gradient(135deg,#3b82f6,#2563eb)!important;color:#fff!important;cursor:pointer;font-weight:650;box-shadow:0 5px 14px rgb(37 99 235 / 18%)!important;transition:transform .15s,filter .15s,border-color .15s}button:hover:not(:disabled){filter:brightness(1.1);transform:translateY(-1px)}button:active:not(:disabled){transform:translateY(0)}button:disabled{cursor:not-allowed;opacity:.55;box-shadow:none!important}input,select{background:#0b1220!important;color:#f8fafc!important;outline:none;transition:border-color .15s,box-shadow .15s}input:hover,select:hover{border-color:#64748b}input:focus,select:focus{border-color:#60a5fa;box-shadow:0 0 0 3px rgb(59 130 246 / 20%)}input[readonly]{background:#111827!important;color:#9fb0c7!important}
button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid rgb(96 165 250 / 62%)!important;outline-offset:2px}label{color:#c9d8ec!important;font-size:.86rem;font-weight:650}
dialog{padding:26px!important;border:1px solid #46546b!important;border-radius:16px!important;background:linear-gradient(145deg,#182236,#111827)!important;color:var(--text)!important;box-shadow:0 30px 90px rgb(0 0 0 / 58%)}dialog::backdrop{background:rgb(2 6 23 / 78%)!important;backdrop-filter:blur(4px)}dialog h2,dialog h3{margin-top:0}.actions{display:flex;justify-content:flex-end;gap:9px;margin-top:24px!important}.actions button{min-width:96px}.actions button:not(:last-child):not(.danger){border-color:#475569;background:#253147;box-shadow:none}.danger,.leave{border-color:#b91c1c!important;background:linear-gradient(135deg,#dc2626,#991b1b)!important;box-shadow:0 5px 14px rgb(185 28 28 / 18%)}
.empty,.setup,.error-box,.node-card{border:1px solid var(--line)!important;border-radius:14px!important;background:linear-gradient(145deg,rgb(23 32 51 / 92%),rgb(15 23 42 / 92%))!important;box-shadow:0 14px 38px rgb(0 0 0 / 16%)}.empty,.setup,.error-box{padding:22px!important}.node-card{padding:20px!important}.status-dot{box-shadow:0 0 0 4px rgb(255 255 255 / 5%),0 0 18px currentColor!important}.status-dot.online,.network-status.ok{color:var(--success);background:var(--success)!important}.status-dot.offline,.network-status.error{color:var(--danger);background:var(--danger)!important}
.toggle,.media-toggle-label input[type="checkbox"]{box-sizing:border-box!important;width:44px!important;min-width:44px!important;max-width:44px!important;height:24px!important;min-height:24px!important;max-height:24px!important;flex:0 0 44px!important;padding:0!important;border:0!important;border-radius:999px!important;background:#4b5563!important;box-shadow:none!important}.toggle[aria-checked="true"],.media-toggle-label input[type="checkbox"]:checked{background:#2563eb!important}.camera-link,.copy-path{border-color:#475569!important;background:#1e293b!important;color:#bfdbfe!important;box-shadow:none!important}.info-button{width:22px!important;min-width:22px;height:22px!important;min-height:22px!important;padding:0!important;border:1px solid #64748b!important;border-radius:50%!important;background:#1e293b!important;color:#bfdbfe!important;line-height:20px!important;box-shadow:none!important}.notice{border-color:#3b82f6!important;border-radius:14px!important;background:#172a47!important;box-shadow:0 20px 55px rgb(0 0 0 / 42%)!important}
@media(max-width:900px){body{padding:18px 14px 40px}.main-nav{position:static;align-items:stretch;flex-wrap:wrap}.main-nav .brand{flex:1 0 calc(100% - 190px)}.main-nav>a{flex:1;text-align:center;white-space:nowrap}#network-info{margin-bottom:28px!important}.table-wrap,body>table{overflow-x:auto}table{display:block;white-space:nowrap}}
@media(max-width:600px){.main-nav .brand{flex-basis:100%;margin:4px 6px 8px!important}.main-nav #internet-status{margin:0 6px 8px}.main-nav>a{flex-basis:calc(50% - 6px)}#network-info{align-items:flex-start;flex-direction:column;margin-inline:5px!important}h1{font-size:1.7rem}dialog{padding:20px!important}.actions{flex-wrap:wrap}.actions button{flex:1}.notice{right:12px!important;bottom:12px!important;left:12px;min-width:0!important}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;transition:none!important}}
`
